### ISSUE TITLE
Extra color code

### ISSUE THREAD

**Issue by danielb2** [bucaran/clor#5]
``` javascript
> var Chalk = require('chalk');
undefined
> var Clor = require('clor');
undefined
> Chalk.red('red')
'\u001b[31mred\u001b[39m'
> Clor.red('red').toString()
'\u001b[31mred\u001b[0m\u001b[0m'
```

Note how Clor has extra `\u001b[0m` at the end.

Also in the case of: ` Clor['red']('red').yellow('moo').toString()` which produces: `\u001b[31mred\u001b[0m\u001b[33mmoo\u001b[0m\u001b[0m`

This can be reduced to: `\u001b[31mred\u001b[33mmoo\u001b[0m`

Again there seems to be extra at  `\u001b[0m` at the end.

Or am I missing something?

**Comment by danielb2** [comment]
Hello?

**Comment by chrismendis** [comment]
@danielb2 I've implemented a fix and submitted a PR to @bucaran.

**Comment by bucaran** [comment]
@danielb2 Hi Daniel, sorry for the lack of response on my part. Really busy last week.

@chrismendis Thanks, will merge ASAP. I left you a question in the PR comment thread.
